name: CI
on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "build ubuntuweb"
        id: latest_tag
        run: bash fetch_build 
      - name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
         name: Artifacts
         path: ./ubuntu-web-liveinstcd.iso
